In [55]:
import numpy as np
from scipy.io import loadmat
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt
from tensorflow.keras.activations import sigmoid

In [48]:
# use tensorflow!
model = Sequential(
    [
        tf.keras.Input(shape = (400,)),
        Dense(25, activation = 'sigmoid'),
        Dense(15, activation = 'sigmoid'),
        Dense(1, activation = 'sigmoid')
    ], name = "my-model"
)

In [49]:
model.summary()

Model: "my-model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 25)                10025     
                                                                 
 dense_7 (Dense)             (None, 15)                390       
                                                                 
 dense_8 (Dense)             (None, 1)                 16        
                                                                 
Total params: 10,431
Trainable params: 10,431
Non-trainable params: 0
_________________________________________________________________


In [50]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [51]:
# numpy model implementation
def my_dense(a_in, W, b, g) :
    units = W.shape[1]
    a_out = np.zeros(units)
    for j in range(units) :
        w = W[:, j]
        z = np.dot(a_in, w) + b[j]
        a_out[j] = g(z)
    return a_out

In [52]:
def my_sequential(x, W1, b1, W2, b2, W3, b3) :
    a1 = my_dense(x, W1, b1, sigmoid)
    a2 = my_dense(a1, W2, b2, sigmoid)
    a3 = my_dense(a2, W3, b3, sigmoid)
    return a3

In [56]:
# test 
x_test = 0.1 * np.arange(1, 3, 1).reshape(2,)
W_test = 0.1 * np.arange(1, 7, 1).reshape(2, 3)
b_test = 0.1 * np.arange(1, 4, 1).reshape(3,)
A_test = my_dense(x_test, W_test, b_test, sigmoid)
print(A_test)

[0.54735762 0.57932425 0.61063923]


In [53]:
# vectorized numpy model implementation
def my_dense_v(a_in, W, b, g) :
    z = np.matmul(a_in, W) + b
    A_out = g(z)
    return A_out

In [54]:
def my_sequential_v(X, W1, b1, W2, b2, W3, b3) :
    A1 = my_dense_v(X, W1, b1, sigmoid)
    A2 = my_dense_v(A1, W2, b2, sigmoid)
    A3 = my_dense_v(A2, W3, b3, sigmoid)
    return A3

In [57]:
# test
X_test = 0.1 * np.arange(1, 9, 1).reshape(4, 2)
W_test = 0.1 * np.arange(1, 7, 1).reshape(2, 3)
B_test = 0.1 * np.arange(1, 4, 1).reshape(1, 3)
A_test = my_dense_v(X_test, W_test, B_test, sigmoid)
print(A_test)

tf.Tensor(
[[0.54735762 0.57932425 0.61063923]
 [0.57199613 0.61301418 0.65248946]
 [0.5962827  0.64565631 0.6921095 ]
 [0.62010643 0.67699586 0.72908792]], shape=(4, 3), dtype=float64)
