In [3]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
%matplotlib widget
from matplotlib.widgets import Slider

In [4]:
def my_softmax(z) :
    ez = np.exp(z)
    sm = ez / np.sum(ez)
    return sm

In [11]:
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples = 2000, centers = centers, cluster_std = 1.0, random_state = 30)

In [12]:
model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')
    ]
)
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001),
)
model.fit(
    X_train, y_train,
    epochs = 10
)

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 1.0651
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.4370
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1745
Epoch 4/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1001
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0740
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0610
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0530
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0473
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0431
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0396


In [13]:
p_non = model.predict(X_train)
print(p_non[:2])
print("largest : ", np.max(p_non), " smallest : ", np.min(p_non))

63/63 [==============================] - 0s 2ms/step
[[2.3711785e-03 2.5088575e-03 9.7405225e-01 2.1067739e-02]
 [9.9376810e-01 4.2061093e-03 1.9406951e-03 8.5041938e-05]]
largest :  0.99999833  smallest :  1.0787942e-09


In [18]:

# better way
p_model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')
    ]
)
p_model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True),
    optimizer = tf.keras.optimizers.Adam(0.001)
)
p_model.fit(
    X_train, y_train,
    epochs = 10
)

Epoch 1/10
63/63 [==============================] - 0s 2ms/step - loss: 1.2318
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.5316
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.2347
Epoch 4/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1372
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0994
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0796
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0686
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0615
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0562
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0524


In [19]:
p_preferred = p_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 [==============================] - 0s 1ms/step
two example output vectors:
 [[-2.5904179 -4.362497   1.5716958 -2.397447 ]
 [ 2.118403  -1.9984552 -9.144973  -8.845713 ]]
largest value 7.5999136 smallest value -16.344753


In [21]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[1.5017289e-02 2.5526274e-03 9.6421647e-01 1.8213680e-02]
 [9.8393643e-01 1.6033867e-02 1.2628301e-05 1.7033832e-05]]
largest value 0.9999944 smallest value 2.54815e-09


In [22]:
# find index of most likely category
for i in range(5) :
    print(f"{p_preferred[i]}, category : {np.argmax(p_preferred[i])}")

[-2.5904179 -4.362497   1.5716958 -2.397447 ], category : 2
[ 2.118403  -1.9984552 -9.144973  -8.845713 ], category : 0
[ 1.409015  -1.1661719 -7.0922627 -6.9418015], category : 0
[-0.7424744  3.399872  -4.147137  -2.205473 ], category : 1
[-2.1139026 -9.536554   2.940944  -6.4332566], category : 2
